services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secretnote
    ports:
      - '5432:5432'
  api:
    build: .
    environment:
      DATABASE_URL: postgres://username:password@db:5432/secretnote
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
