services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secretnotes
    ports:
      - '5432:5432'

  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/secretnotes
    command: npm run test
    depends_on:
      - db
